// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(Contextedb))]
    [Migration("20260729110619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back.Models.Client", b =>
                {
                    b.Property<int>("ID_CLIENT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CLIENT"));

                    b.Property<string>("EMAIL_CLIENT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NOM_CLIENT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PRENOM_CLIENT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_CLIENT");

                    b.ToTable("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
