// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(Contextedb))]
    partial class ContextedbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClasseModele_avion", b =>
                {
                    b.Property<string>("Classescode_classe")
                        .HasColumnType("text");

                    b.Property<string>("Modele_Avionscode_modele")
                        .HasColumnType("text");

                    b.HasKey("Classescode_classe", "Modele_Avionscode_modele");

                    b.HasIndex("Modele_Avionscode_modele");

                    b.ToTable("ClasseModele_avion");
                });

            modelBuilder.Entity("back.Models.Affecter", b =>
                {
                    b.Property<string>("fk_id_pilote")
                        .HasColumnType("text");

                    b.Property<string>("fk_id_vol")
                        .HasColumnType("text");

                    b.HasKey("fk_id_pilote", "fk_id_vol");

                    b.HasIndex("fk_id_vol");

                    b.ToTable("Affecter");
                });

            modelBuilder.Entity("back.Models.Avion", b =>
                {
                    b.Property<string>("id_avion")
                        .HasColumnType("text");

                    b.Property<string>("Placenumero_place")
                        .HasColumnType("text");

                    b.Property<string>("Statut_avioncode_statut")
                        .HasColumnType("text");

                    b.Property<string>("fk_code_modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_id_compagnie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom_avion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_avion");

                    b.HasIndex("Placenumero_place");

                    b.HasIndex("Statut_avioncode_statut");

                    b.HasIndex("fk_code_modele");

                    b.HasIndex("fk_id_compagnie");

                    b.ToTable("Avion");
                });

            modelBuilder.Entity("back.Models.Billet", b =>
                {
                    b.Property<int>("numero_billet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("numero_billet"));

                    b.Property<string>("fk_id_vol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_passeport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("numero_billet");

                    b.HasIndex("fk_id_vol");

                    b.HasIndex("fk_passeport");

                    b.ToTable("Billet");
                });

            modelBuilder.Entity("back.Models.Caracteriser", b =>
                {
                    b.Property<string>("fk_code_statut")
                        .HasColumnType("text");

                    b.Property<string>("fk_id_avion")
                        .HasColumnType("text");

                    b.HasKey("fk_code_statut", "fk_id_avion");

                    b.HasIndex("fk_id_avion");

                    b.ToTable("Caracteriser");
                });

            modelBuilder.Entity("back.Models.Classe", b =>
                {
                    b.Property<string>("code_classe")
                        .HasColumnType("text");

                    b.Property<string>("Placenumero_place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("libelle_classe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code_classe");

                    b.HasIndex("Placenumero_place");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("back.Models.Compagnie", b =>
                {
                    b.Property<string>("id_compagnie")
                        .HasColumnType("text");

                    b.Property<string>("email_compagnie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom_compagnie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel_compagnie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_compagnie");

                    b.ToTable("Compagnie");
                });

            modelBuilder.Entity("back.Models.Diviser", b =>
                {
                    b.Property<string>("fk_code_modele")
                        .HasColumnType("text");

                    b.Property<string>("fk_code_classe")
                        .HasColumnType("text");

                    b.HasKey("fk_code_modele", "fk_code_classe");

                    b.HasIndex("fk_code_classe");

                    b.ToTable("Diviser");
                });

            modelBuilder.Entity("back.Models.Modele_avion", b =>
                {
                    b.Property<string>("code_modele")
                        .HasColumnType("text");

                    b.Property<string>("libelle_modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code_modele");

                    b.ToTable("Modele_avion");
                });

            modelBuilder.Entity("back.Models.Passager", b =>
                {
                    b.Property<string>("passeport")
                        .HasColumnType("text");

                    b.Property<string>("categorie_passager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom_passager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prenom_passager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel_passager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("passeport");

                    b.ToTable("Passager");
                });

            modelBuilder.Entity("back.Models.Pilote", b =>
                {
                    b.Property<string>("id_pilote")
                        .HasColumnType("text");

                    b.Property<string>("nom_pilote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prenom_pilote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel_pilote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_pilote");

                    b.ToTable("Pilote");
                });

            modelBuilder.Entity("back.Models.Place", b =>
                {
                    b.Property<string>("numero_place")
                        .HasColumnType("text");

                    b.HasKey("numero_place");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("back.Models.Posseder", b =>
                {
                    b.Property<string>("fk_id_avion")
                        .HasColumnType("text");

                    b.Property<string>("fk_numero_place")
                        .HasColumnType("text");

                    b.HasKey("fk_id_avion", "fk_numero_place");

                    b.HasIndex("fk_numero_place");

                    b.ToTable("Posseder");
                });

            modelBuilder.Entity("back.Models.Regrouper", b =>
                {
                    b.Property<string>("fk_code_classe")
                        .HasColumnType("text");

                    b.Property<string>("fk_numero_place")
                        .HasColumnType("text");

                    b.HasKey("fk_code_classe", "fk_numero_place");

                    b.ToTable("Regrouper");
                });

            modelBuilder.Entity("back.Models.Reservation", b =>
                {
                    b.Property<string>("id_reservation")
                        .HasColumnType("text");

                    b.Property<string>("date_reservation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_numero_place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_passeport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("valide")
                        .HasColumnType("integer");

                    b.HasKey("id_reservation");

                    b.HasIndex("fk_numero_place");

                    b.HasIndex("fk_passeport");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("back.Models.Statut_avion", b =>
                {
                    b.Property<string>("code_statut")
                        .HasColumnType("text");

                    b.Property<string>("libelle_statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code_statut");

                    b.ToTable("Statut_avion");
                });

            modelBuilder.Entity("back.Models.Trajet", b =>
                {
                    b.Property<string>("id_trajet")
                        .HasColumnType("text");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lieu_depart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_trajet");

                    b.ToTable("Trajet");
                });

            modelBuilder.Entity("back.Models.Vol", b =>
                {
                    b.Property<string>("id_vol")
                        .HasColumnType("text");

                    b.Property<string>("date_arrivee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("date_depart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_id_avion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_id_trajet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_vol");

                    b.HasIndex("fk_id_avion");

                    b.HasIndex("fk_id_trajet");

                    b.ToTable("Vol");
                });

            modelBuilder.Entity("ClasseModele_avion", b =>
                {
                    b.HasOne("back.Models.Classe", null)
                        .WithMany()
                        .HasForeignKey("Classescode_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Models.Modele_avion", null)
                        .WithMany()
                        .HasForeignKey("Modele_Avionscode_modele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back.Models.Affecter", b =>
                {
                    b.HasOne("back.Models.Pilote", "Pilote")
                        .WithMany("Affecters")
                        .HasForeignKey("fk_id_pilote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_affecter_pilote");

                    b.HasOne("back.Models.Vol", "Vol")
                        .WithMany("Affecters")
                        .HasForeignKey("fk_id_vol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_affecter_vol");

                    b.Navigation("Pilote");

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("back.Models.Avion", b =>
                {
                    b.HasOne("back.Models.Place", null)
                        .WithMany("Avions")
                        .HasForeignKey("Placenumero_place");

                    b.HasOne("back.Models.Statut_avion", null)
                        .WithMany("Avions")
                        .HasForeignKey("Statut_avioncode_statut");

                    b.HasOne("back.Models.Modele_avion", "Modele_avion")
                        .WithMany("Avions")
                        .HasForeignKey("fk_code_modele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avion_modele");

                    b.HasOne("back.Models.Compagnie", "Compagnie")
                        .WithMany("Avions")
                        .HasForeignKey("fk_id_compagnie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avion_compagnie");

                    b.Navigation("Compagnie");

                    b.Navigation("Modele_avion");
                });

            modelBuilder.Entity("back.Models.Billet", b =>
                {
                    b.HasOne("back.Models.Vol", "Vol")
                        .WithMany("Billets")
                        .HasForeignKey("fk_id_vol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_billet_vol");

                    b.HasOne("back.Models.Passager", "Passager")
                        .WithMany("Billets")
                        .HasForeignKey("fk_passeport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_billet_passager");

                    b.Navigation("Passager");

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("back.Models.Caracteriser", b =>
                {
                    b.HasOne("back.Models.Statut_avion", "Statut_avion")
                        .WithMany("Caracterisers")
                        .HasForeignKey("fk_code_statut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caracteriser_statut_avion");

                    b.HasOne("back.Models.Avion", "Avion")
                        .WithMany("Caracterisers")
                        .HasForeignKey("fk_id_avion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caracteriser_avion");

                    b.Navigation("Avion");

                    b.Navigation("Statut_avion");
                });

            modelBuilder.Entity("back.Models.Classe", b =>
                {
                    b.HasOne("back.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("Placenumero_place")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("back.Models.Diviser", b =>
                {
                    b.HasOne("back.Models.Classe", "Classe")
                        .WithMany("Divisers")
                        .HasForeignKey("fk_code_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diviser_classe");

                    b.HasOne("back.Models.Modele_avion", "Modele_avion")
                        .WithMany("Divisers")
                        .HasForeignKey("fk_code_modele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diviser_modele_avion");

                    b.Navigation("Classe");

                    b.Navigation("Modele_avion");
                });

            modelBuilder.Entity("back.Models.Posseder", b =>
                {
                    b.HasOne("back.Models.Avion", "Avion")
                        .WithMany("Posseders")
                        .HasForeignKey("fk_id_avion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posseder_avion");

                    b.HasOne("back.Models.Place", "Place")
                        .WithMany("Posseders")
                        .HasForeignKey("fk_numero_place")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posseder_place");

                    b.Navigation("Avion");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("back.Models.Regrouper", b =>
                {
                    b.HasOne("back.Models.Classe", "Classe")
                        .WithMany("Regroupers")
                        .HasForeignKey("fk_code_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regrouper_classe");

                    b.HasOne("back.Models.Place", "Place")
                        .WithMany("Regroupers")
                        .HasForeignKey("fk_code_classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regrouper_place");

                    b.Navigation("Classe");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("back.Models.Reservation", b =>
                {
                    b.HasOne("back.Models.Place", "Place")
                        .WithMany("Reservations")
                        .HasForeignKey("fk_numero_place")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_place");

                    b.HasOne("back.Models.Passager", "Passager")
                        .WithMany("Reservations")
                        .HasForeignKey("fk_passeport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_passager");

                    b.Navigation("Passager");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("back.Models.Vol", b =>
                {
                    b.HasOne("back.Models.Avion", "Avion")
                        .WithMany("Vols")
                        .HasForeignKey("fk_id_avion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vol_avion");

                    b.HasOne("back.Models.Trajet", "Trajet")
                        .WithMany("Vols")
                        .HasForeignKey("fk_id_trajet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vol_trajet");

                    b.Navigation("Avion");

                    b.Navigation("Trajet");
                });

            modelBuilder.Entity("back.Models.Avion", b =>
                {
                    b.Navigation("Caracterisers");

                    b.Navigation("Posseders");

                    b.Navigation("Vols");
                });

            modelBuilder.Entity("back.Models.Classe", b =>
                {
                    b.Navigation("Divisers");

                    b.Navigation("Regroupers");
                });

            modelBuilder.Entity("back.Models.Compagnie", b =>
                {
                    b.Navigation("Avions");
                });

            modelBuilder.Entity("back.Models.Modele_avion", b =>
                {
                    b.Navigation("Avions");

                    b.Navigation("Divisers");
                });

            modelBuilder.Entity("back.Models.Passager", b =>
                {
                    b.Navigation("Billets");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("back.Models.Pilote", b =>
                {
                    b.Navigation("Affecters");
                });

            modelBuilder.Entity("back.Models.Place", b =>
                {
                    b.Navigation("Avions");

                    b.Navigation("Posseders");

                    b.Navigation("Regroupers");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("back.Models.Statut_avion", b =>
                {
                    b.Navigation("Avions");

                    b.Navigation("Caracterisers");
                });

            modelBuilder.Entity("back.Models.Trajet", b =>
                {
                    b.Navigation("Vols");
                });

            modelBuilder.Entity("back.Models.Vol", b =>
                {
                    b.Navigation("Affecters");

                    b.Navigation("Billets");
                });
#pragma warning restore 612, 618
        }
    }
}
