--
-- PostgreSQL database dump
--

\restrict JRkRcPwCGOY9wb0vsvIa9CrMIMZ6Dq0GtrCvaxuxGk94XpLaxYtxUjDRXhpYekH

-- Dumped from database version 18.4 (Ubuntu 18.4-1.pgdg22.04+1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Affecter; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Affecter" (
    fk_id_vol text NOT NULL,
    fk_id_pilote text NOT NULL
);


ALTER TABLE public."Affecter" OWNER TO root;

--
-- Name: Avion; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Avion" (
    id_avion text NOT NULL,
    nom_avion text NOT NULL,
    fk_id_compagnie text NOT NULL,
    "Placenumero_place" text,
    "Statut_avioncode_statut" text
);


ALTER TABLE public."Avion" OWNER TO root;

--
-- Name: Billet; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Billet" (
    numero_billet integer NOT NULL,
    fk_passeport text NOT NULL,
    fk_id_vol text NOT NULL
);


ALTER TABLE public."Billet" OWNER TO root;

--
-- Name: Billet_numero_billet_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Billet" ALTER COLUMN numero_billet ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Billet_numero_billet_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Caracteriser; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Caracteriser" (
    fk_code_statut text NOT NULL,
    fk_id_avion text NOT NULL
);


ALTER TABLE public."Caracteriser" OWNER TO root;

--
-- Name: Compagnie; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Compagnie" (
    id_compagnie text NOT NULL,
    nom_compagnie text NOT NULL,
    tel_compagnie text NOT NULL,
    email_compagnie text NOT NULL
);


ALTER TABLE public."Compagnie" OWNER TO root;

--
-- Name: Date_vol; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Date_vol" (
    date_depart text NOT NULL
);


ALTER TABLE public."Date_vol" OWNER TO root;

--
-- Name: Passager; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Passager" (
    passeport text NOT NULL,
    nom_passager text NOT NULL,
    prenom_passager text NOT NULL,
    tel_passager text NOT NULL,
    categorie_passager text NOT NULL
);


ALTER TABLE public."Passager" OWNER TO root;

--
-- Name: Pilote; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Pilote" (
    id_pilote text NOT NULL,
    nom_pilote text NOT NULL,
    prenom_pilote text NOT NULL,
    tel_pilote text NOT NULL
);


ALTER TABLE public."Pilote" OWNER TO root;

--
-- Name: Place; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Place" (
    numero_place text NOT NULL,
    classe_siege text NOT NULL,
    occupee integer NOT NULL
);


ALTER TABLE public."Place" OWNER TO root;

--
-- Name: Posseder; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Posseder" (
    fk_numero_place text NOT NULL,
    fk_id_avion text NOT NULL
);


ALTER TABLE public."Posseder" OWNER TO root;

--
-- Name: Repartir; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Repartir" (
    fk_id_compagnie text NOT NULL,
    fk_id_trajet text NOT NULL
);


ALTER TABLE public."Repartir" OWNER TO root;

--
-- Name: Reservation; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Reservation" (
    id_reservation text NOT NULL,
    date_reservation text NOT NULL,
    valide integer NOT NULL,
    fk_numero_place text NOT NULL,
    fk_passeport text NOT NULL,
    fk_id_vol text NOT NULL
);


ALTER TABLE public."Reservation" OWNER TO root;

--
-- Name: Statut_avion; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Statut_avion" (
    code_statut text NOT NULL,
    libelle_statut text NOT NULL
);


ALTER TABLE public."Statut_avion" OWNER TO root;

--
-- Name: Trajet; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Trajet" (
    id_trajet text NOT NULL,
    lieu_depart text NOT NULL,
    destination text NOT NULL
);


ALTER TABLE public."Trajet" OWNER TO root;

--
-- Name: Vol; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Vol" (
    id_vol text NOT NULL,
    fk_date_depart text NOT NULL,
    fk_id_trajet text NOT NULL,
    fk_id_avion text NOT NULL
);


ALTER TABLE public."Vol" OWNER TO root;

--
-- Name: Affecter PK_Affecter; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Affecter"
    ADD CONSTRAINT "PK_Affecter" PRIMARY KEY (fk_id_pilote, fk_id_vol);


--
-- Name: Avion PK_Avion; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Avion"
    ADD CONSTRAINT "PK_Avion" PRIMARY KEY (id_avion);


--
-- Name: Billet PK_Billet; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Billet"
    ADD CONSTRAINT "PK_Billet" PRIMARY KEY (numero_billet);


--
-- Name: Caracteriser PK_Caracteriser; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Caracteriser"
    ADD CONSTRAINT "PK_Caracteriser" PRIMARY KEY (fk_code_statut, fk_id_avion);


--
-- Name: Compagnie PK_Compagnie; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Compagnie"
    ADD CONSTRAINT "PK_Compagnie" PRIMARY KEY (id_compagnie);


--
-- Name: Date_vol PK_Date_vol; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Date_vol"
    ADD CONSTRAINT "PK_Date_vol" PRIMARY KEY (date_depart);


--
-- Name: Passager PK_Passager; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Passager"
    ADD CONSTRAINT "PK_Passager" PRIMARY KEY (passeport);


--
-- Name: Pilote PK_Pilote; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Pilote"
    ADD CONSTRAINT "PK_Pilote" PRIMARY KEY (id_pilote);


--
-- Name: Place PK_Place; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Place"
    ADD CONSTRAINT "PK_Place" PRIMARY KEY (numero_place);


--
-- Name: Posseder PK_Posseder; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Posseder"
    ADD CONSTRAINT "PK_Posseder" PRIMARY KEY (fk_id_avion, fk_numero_place);


--
-- Name: Repartir PK_Repartir; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Repartir"
    ADD CONSTRAINT "PK_Repartir" PRIMARY KEY (fk_id_compagnie, fk_id_trajet);


--
-- Name: Reservation PK_Reservation; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Reservation"
    ADD CONSTRAINT "PK_Reservation" PRIMARY KEY (id_reservation);


--
-- Name: Statut_avion PK_Statut_avion; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Statut_avion"
    ADD CONSTRAINT "PK_Statut_avion" PRIMARY KEY (code_statut);


--
-- Name: Trajet PK_Trajet; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Trajet"
    ADD CONSTRAINT "PK_Trajet" PRIMARY KEY (id_trajet);


--
-- Name: Vol PK_Vol; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Vol"
    ADD CONSTRAINT "PK_Vol" PRIMARY KEY (id_vol);


--
-- Name: IX_Affecter_fk_id_vol; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Affecter_fk_id_vol" ON public."Affecter" USING btree (fk_id_vol);


--
-- Name: IX_Avion_Placenumero_place; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Avion_Placenumero_place" ON public."Avion" USING btree ("Placenumero_place");


--
-- Name: IX_Avion_Statut_avioncode_statut; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Avion_Statut_avioncode_statut" ON public."Avion" USING btree ("Statut_avioncode_statut");


--
-- Name: IX_Avion_fk_id_compagnie; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Avion_fk_id_compagnie" ON public."Avion" USING btree (fk_id_compagnie);


--
-- Name: IX_Billet_fk_id_vol; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Billet_fk_id_vol" ON public."Billet" USING btree (fk_id_vol);


--
-- Name: IX_Billet_fk_passeport; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Billet_fk_passeport" ON public."Billet" USING btree (fk_passeport);


--
-- Name: IX_Caracteriser_fk_id_avion; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Caracteriser_fk_id_avion" ON public."Caracteriser" USING btree (fk_id_avion);


--
-- Name: IX_Posseder_fk_numero_place; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Posseder_fk_numero_place" ON public."Posseder" USING btree (fk_numero_place);


--
-- Name: IX_Repartir_fk_id_trajet; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Repartir_fk_id_trajet" ON public."Repartir" USING btree (fk_id_trajet);


--
-- Name: IX_Reservation_fk_id_vol; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Reservation_fk_id_vol" ON public."Reservation" USING btree (fk_id_vol);


--
-- Name: IX_Reservation_fk_numero_place; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Reservation_fk_numero_place" ON public."Reservation" USING btree (fk_numero_place);


--
-- Name: IX_Reservation_fk_passeport; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Reservation_fk_passeport" ON public."Reservation" USING btree (fk_passeport);


--
-- Name: IX_Vol_fk_date_depart; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Vol_fk_date_depart" ON public."Vol" USING btree (fk_date_depart);


--
-- Name: IX_Vol_fk_id_avion; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Vol_fk_id_avion" ON public."Vol" USING btree (fk_id_avion);


--
-- Name: IX_Vol_fk_id_trajet; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Vol_fk_id_trajet" ON public."Vol" USING btree (fk_id_trajet);


--
-- Name: Avion FK_Avion_Place_Placenumero_place; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Avion"
    ADD CONSTRAINT "FK_Avion_Place_Placenumero_place" FOREIGN KEY ("Placenumero_place") REFERENCES public."Place"(numero_place);


--
-- Name: Avion FK_Avion_Statut_avion_Statut_avioncode_statut; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Avion"
    ADD CONSTRAINT "FK_Avion_Statut_avion_Statut_avioncode_statut" FOREIGN KEY ("Statut_avioncode_statut") REFERENCES public."Statut_avion"(code_statut);


--
-- Name: Affecter fk_affecter_pilote; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Affecter"
    ADD CONSTRAINT fk_affecter_pilote FOREIGN KEY (fk_id_pilote) REFERENCES public."Pilote"(id_pilote) ON DELETE CASCADE;


--
-- Name: Affecter fk_affecter_vol; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Affecter"
    ADD CONSTRAINT fk_affecter_vol FOREIGN KEY (fk_id_vol) REFERENCES public."Vol"(id_vol) ON DELETE CASCADE;


--
-- Name: Avion fk_avion_compagnie; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Avion"
    ADD CONSTRAINT fk_avion_compagnie FOREIGN KEY (fk_id_compagnie) REFERENCES public."Compagnie"(id_compagnie) ON DELETE CASCADE;


--
-- Name: Billet fk_billet_passager; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Billet"
    ADD CONSTRAINT fk_billet_passager FOREIGN KEY (fk_passeport) REFERENCES public."Passager"(passeport) ON DELETE CASCADE;


--
-- Name: Billet fk_billet_vol; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Billet"
    ADD CONSTRAINT fk_billet_vol FOREIGN KEY (fk_id_vol) REFERENCES public."Vol"(id_vol) ON DELETE CASCADE;


--
-- Name: Caracteriser fk_caracteriser_avion; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Caracteriser"
    ADD CONSTRAINT fk_caracteriser_avion FOREIGN KEY (fk_id_avion) REFERENCES public."Avion"(id_avion) ON DELETE CASCADE;


--
-- Name: Caracteriser fk_caracteriser_statut_avion; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Caracteriser"
    ADD CONSTRAINT fk_caracteriser_statut_avion FOREIGN KEY (fk_code_statut) REFERENCES public."Statut_avion"(code_statut) ON DELETE CASCADE;


--
-- Name: Posseder fk_posseder_avion; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Posseder"
    ADD CONSTRAINT fk_posseder_avion FOREIGN KEY (fk_id_avion) REFERENCES public."Avion"(id_avion) ON DELETE CASCADE;


--
-- Name: Posseder fk_posseder_place; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Posseder"
    ADD CONSTRAINT fk_posseder_place FOREIGN KEY (fk_numero_place) REFERENCES public."Place"(numero_place) ON DELETE CASCADE;


--
-- Name: Repartir fk_repartir_compagnie; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Repartir"
    ADD CONSTRAINT fk_repartir_compagnie FOREIGN KEY (fk_id_compagnie) REFERENCES public."Compagnie"(id_compagnie) ON DELETE CASCADE;


--
-- Name: Repartir fk_repartir_trajet; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Repartir"
    ADD CONSTRAINT fk_repartir_trajet FOREIGN KEY (fk_id_trajet) REFERENCES public."Trajet"(id_trajet) ON DELETE CASCADE;


--
-- Name: Reservation fk_reservation_passager; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Reservation"
    ADD CONSTRAINT fk_reservation_passager FOREIGN KEY (fk_passeport) REFERENCES public."Passager"(passeport) ON DELETE CASCADE;


--
-- Name: Reservation fk_reservation_place; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Reservation"
    ADD CONSTRAINT fk_reservation_place FOREIGN KEY (fk_numero_place) REFERENCES public."Place"(numero_place) ON DELETE CASCADE;


--
-- Name: Reservation fk_reservation_vol; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Reservation"
    ADD CONSTRAINT fk_reservation_vol FOREIGN KEY (fk_id_vol) REFERENCES public."Vol"(id_vol) ON DELETE CASCADE;


--
-- Name: Vol fk_vol_avion; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Vol"
    ADD CONSTRAINT fk_vol_avion FOREIGN KEY (fk_id_avion) REFERENCES public."Avion"(id_avion) ON DELETE CASCADE;


--
-- Name: Vol fk_vol_date_vol; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Vol"
    ADD CONSTRAINT fk_vol_date_vol FOREIGN KEY (fk_date_depart) REFERENCES public."Date_vol"(date_depart) ON DELETE CASCADE;


--
-- Name: Vol fk_vol_trajet; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Vol"
    ADD CONSTRAINT fk_vol_trajet FOREIGN KEY (fk_id_trajet) REFERENCES public."Trajet"(id_trajet) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict JRkRcPwCGOY9wb0vsvIa9CrMIMZ6Dq0GtrCvaxuxGk94XpLaxYtxUjDRXhpYekH

